[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "https://afwajarental.com/*"
  to = "https://www.afwajarental.my/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.afwajarental.com/*"
  to = "https://www.afwajarental.my/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/logistics"
  to = "/logistics.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/refund-policy"
  to = "/refund-policy.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/price-reference"
  to = "/price-reference.html"
  status = 200

[[redirects]]
  from = "/info-tips"
  to = "/panduan.html"
  status = 200

[[redirects]]
  from = "/panduan"
  to = "/info-tips"
  status = 301
  force = true

[[redirects]]
  from = "/fleet"
  to = "/fleet.html"
  status = 200

[[redirects]]
  from = "/driver-transfer"
  to = "/driver-transfer.html"
  status = 200

[[redirects]]
  from = "/kereta-sewa-cyberjaya"
  to = "/kereta-sewa-cyberjaya.html"
  status = 200

[[redirects]]
  from = "/kereta-sewa-klia"
  to = "/kereta-sewa-klia.html"
  status = 200

[[redirects]]
  from = "/kereta-sewa-putrajaya"
  to = "/kereta-sewa-putrajaya.html"
  status = 200
