(function () {
    const { createLanguageController, setCurrentYear } = window.AfwajaSite;

    const translations = {
        en: {
            nav_back: "Back to Home",
            header_title: "Rental Terms and Conditions",
            header_desc: "Please read and understand Afwaja Car Rental's policies and terms before making a booking.",
            sec1_title: "Online Booking",
            sec1_p1: "For online bookings, confirmation will be sent via email within one (1) hour.",
            sec1_p2: "If the vehicle is unavailable, a full refund will be issued.",
            sec2_title: "Delivery & Collection Charges",
            sec2_desc: "Delivery and return pickup charges are calculated based on the actual road distance from Afwaja Car Rental Cyberjaya.",
            sec2_l1: "Self pickup / self return at Afwaja Car Rental Cyberjaya",
            sec2_l2: "Delivery to the pick-up location",
            sec2_l3: "Return pickup from the return location",
            sec2_l4: "Distance calculation",
            sec2_l5: "Total transport charge",
            sec2_v4: "Google Maps",
            sec2_v5: "Calculated automatically",
            sec3_title: "Security Deposit",
            sec3_p1: "A security deposit of RM100 to RM400 per vehicle is required upon collection, depending on the vehicle type.",
            sec3_p2: "The deposit will be refunded within 3 to 14 working days after the vehicle is returned, subject to the vehicle being in good condition with no summons or fines.",
            sec4_title: "Additional Driver, Age Limit & License",
            sec4_sub1: "Additional Driver",
            sec4_p1: "Additional drivers are charged <strong>RM10 per person per day</strong>. All drivers must be registered upon collection. The company reserves the right to impose an RM500 penalty if the vehicle is driven by an unauthorized individual.",
            sec4_sub2: "Age Limit & License",
            sec4_p2: "Drivers must be between 23 and 65 years old.",
            sec4_p3: "Foreign citizens with a valid driving license in English are allowed to drive in Malaysia for a maximum of 3 months.",
            sec4_p4: "Probationary (P) license holders are <strong>not allowed</strong>.",
            sec5_title: "Rental Period, Extension & Mileage",
            sec5_p1: "<strong>Minimum rental period:</strong> One (1) day (24 hours).",
            sec5_p2: "<strong>Late return / extension charge:</strong> The hourly charge is 10% of the daily rental rate. If the total hourly charge exceeds the daily rate, a full day's charge applies.",
            sec5_p3: "<strong>Mileage Limit Policy:</strong> Rental includes 300 km per day. Excess mileage will be charged at RM1 per km.",
            sec6_title: "Vehicle Collection & Verification",
            sec6_sub1: "1. Authorized Renter & Unauthorized Collection",
            sec6_p1: "Only the individual who made the booking and presents a valid ID/passport and driving license is allowed to collect the vehicle. The vehicle will not be handed over to third parties without written consent. If an unauthorized individual attempts collection, the booking will be cancelled (subject to charges).",
            sec6_sub2: "2. Required Documents",
            sec6_p2: "Please bring copies of: ID / Passport, Driving License, and Business Card or proof of address.",
            sec6_sub3: "3. Vehicle Inspection",
            sec6_p3: "The renter must inspect the vehicle upon collection. Any damage must be reported immediately. Unreported damage will be considered the renter's responsibility.",
            sec7_title: "Insurance, Excess & Accidents",
            sec7_desc: "All vehicles are insured, but the renter is responsible for the excess:",
            sec7_t1: "Maximum Excess Rate",
            sec7_l1: "<strong>Group A:</strong> RM4,000",
            sec7_l2: "<strong>Group B:</strong> RM6,000",
            sec7_l3: "<strong>Group C:</strong> RM10,000",
            sec7_l4: "<strong>Group D:</strong> RM20,000",
            sec7_t2: "Vehicle Groups",
            sec7_sub1: "Insurance Exclusions",
            sec7_p1: "Insurance <strong>does not cover</strong>: Negligence/misuse, punctured/burst tires, wrong fuel, battery damage due to negligence, and lost/damaged accessories. Damage is only covered if it involves a collision between two moving vehicles. If the vehicle is damaged while parked, the renter is fully responsible. The undercarriage, windshield, and roof are not covered.",
            sec7_sub2: "Accidents & Administration Fees",
            sec7_p2: "A police report must be made within 24 hours. In the event of an accident, the company may impose an administration fee (covering insurance processing, communication, loss of income) between <strong>RM1,000 &ndash; RM5,000</strong> depending on the vehicle. If the third-party claim fails, the cost is borne by the renter.",
            sec8_title: "Additional Terms, Return & Cancellation",
            sec8_sub1: "Fuel",
            sec8_p1: "Vehicles must be returned with the same fuel level. A surcharge of up to RM300 applies if insufficient.",
            sec8_sub2: "Cleanliness",
            sec8_p2: "If excessively dirty &rarr; RM300 charge. Smoking / bringing pets &rarr; RM500 penalty.",
            sec8_sub3: "Summons & Traffic Tickets",
            sec8_p3: "All summons are the renter's responsibility. Late payment &rarr; RM300 penalty.",
            sec8_sub4: "Speed Limit",
            sec8_p4: "Highway: 110 km/h. Normal roads: 90 km/h.",
            sec8_sub5: "Cancellation Policy",
            sec8_l1: "24 hours prior: Full refund",
            sec8_l2: "Less than 24 hours / No show: No refund",
            sec8_l3: "Change date: Subject to availability",
            sec8_l4: "Company cancels: Full refund or reschedule",
            sec8_sub6: "Return & Termination",
            sec8_p5: "Notify at least 12 hours before returning the car. The company may terminate the rental immediately in case of misuse. The deposit may be forfeited.",
            sec8_sub7: "Criminal Use",
            sec8_p6: "If used for criminal purposes, the renter is fully responsible for the vehicle's value.",
            sec8_sub9: "Outstanding Payments",
            sec8_p8: "If there are any outstanding payments that remain unpaid, the renter's name may be blacklisted in the CTOS system and further action may be taken by the company.",
            sec8_sub8: "Personal Data & Disclaimer",
            sec8_p7: "Data may be shared with relevant agencies for debt collection purposes. By renting, the renter agrees to all terms and conditions.",
            footer_copy: "All Rights Reserved.",
        },
        ms: {
            nav_back: "Kembali ke Laman Utama",
            header_title: "Terma dan Syarat Sewaan",
            header_desc: "Sila baca dan fahami polisi serta terma sewaan Afwaja Car Rental sebelum membuat tempahan.",
            sec1_title: "Tempahan Dalam Talian (Online Booking)",
            sec1_p1: "Bagi tempahan dalam talian, pengesahan akan dihantar melalui emel dalam tempoh satu (1) jam.",
            sec1_p2: "Jika kenderaan tidak tersedia, bayaran akan dipulangkan sepenuhnya (full refund).",
            sec2_title: "Caj Penghantaran & Pengambilan",
            sec2_desc: "Caj penghantaran dan pickup semula dikira berdasarkan jarak jalan sebenar dari Afwaja Car Rental Cyberjaya.",
            sec2_l1: "Ambil sendiri / pulang sendiri di Afwaja Car Rental Cyberjaya",
            sec2_l2: "Penghantaran ke lokasi ambil (Pick-up Location)",
            sec2_l3: "Pickup semula dari lokasi pulang (Return Location)",
            sec2_l4: "Kiraan jarak",
            sec2_l5: "Jumlah caj transport",
            sec2_v4: "Google Maps",
            sec2_v5: "Dikira automatik",
            sec3_title: "Deposit Keselamatan",
            sec3_p1: "Deposit keselamatan sebanyak RM100 hingga RM400 bagi setiap kenderaan akan dikenakan semasa pengambilan, bergantung kepada jenis kenderaan.",
            sec3_p2: "Deposit akan dipulangkan dalam tempoh 3 hingga 14 hari bekerja selepas kenderaan dipulangkan, tertakluk kepada keadaan kenderaan yang baik serta tiada saman atau denda.",
            sec4_title: "Pemandu Tambahan, Had Umur & Lesen",
            sec4_sub1: "Pemandu Tambahan",
            sec4_p1: "Pemandu tambahan dikenakan caj <strong>RM10 seorang sehari</strong>. Semua pemandu mesti didaftarkan semasa pengambilan. Syarikat berhak mengenakan penalti RM500 sekiranya kenderaan dipandu oleh individu yang tidak dibenarkan.",
            sec4_sub2: "Had Umur & Lesen",
            sec4_p2: "Pemandu mestilah berumur antara 23 hingga 65 tahun.",
            sec4_p3: "Warganegara asing yang mempunyai lesen memandu sah dalam Bahasa Inggeris dibenarkan memandu di Malaysia maksimum selama 3 bulan.",
            sec4_p4: "Pemegang lesen percubaan (P) <strong>tidak dibenarkan</strong>.",
            sec5_title: "Tempoh Sewaan, Lanjutan & Perbatuan",
            sec5_p1: "<strong>Tempoh minimum sewaan:</strong> Satu (1) hari (24 jam).",
            sec5_p2: "<strong>Caj lewat pulang / lanjutan:</strong> Caj setiap jam adalah 10% daripada kadar sewaan harian. Jika jumlah caj jam melebihi kadar harian, caj satu hari penuh akan dikenakan.",
            sec5_p3: "<strong>Polisi Had Perbatuan:</strong> Sewaan termasuk 300 km sehari. Lebihan jarak akan dikenakan caj RM1 bagi setiap km.",
            sec6_title: "Pengambilan & Pengesahan Kenderaan",
            sec6_sub1: "1. Penyewa Sah & Pengambilan Tanpa Kebenaran",
            sec6_p1: "Hanya individu yang membuat tempahan dan mengemukakan kad pengenalan/pasport serta lesen memandu yang sah dibenarkan mengambil kenderaan. Kenderaan tidak akan diserahkan kepada pihak lain tanpa kebenaran bertulis. Jika individu tidak dibenarkan cuba mengambil kenderaan, tempahan dibatalkan (tertakluk kepada caj).",
            sec6_sub2: "2. Dokumen Diperlukan",
            sec6_p2: "Sila bawa salinan: Kad pengenalan / Pasport, Lesen memandu, dan Kad perniagaan atau bukti alamat.",
            sec6_sub3: "3. Pemeriksaan Kenderaan",
            sec6_p3: "Penyewa mesti memeriksa kenderaan semasa pengambilan. Sebarang kerosakan mesti dilaporkan segera. Kerosakan yang tidak dilaporkan akan dianggap tanggungjawab penyewa.",
            sec7_title: "Insurans, Lebihan (Excess) & Kemalangan",
            sec7_desc: "Semua kenderaan dilindungi insurans, namun penyewa bertanggungjawab ke atas lebihan (Excess):",
            sec7_t1: "Kadar Lebihan Maksimum",
            sec7_l1: "<strong>Kumpulan A:</strong> RM4,000",
            sec7_l2: "<strong>Kumpulan B:</strong> RM6,000",
            sec7_l3: "<strong>Kumpulan C:</strong> RM10,000",
            sec7_l4: "<strong>Kumpulan D:</strong> RM20,000",
            sec7_t2: "Kumpulan Kenderaan",
            sec7_sub1: "Pengecualian Insurans",
            sec7_p1: "Insurans <strong>tidak melindungi</strong>: Kecuaian/salah guna, tayar pancit/pecah, kesilapan isi minyak, kerosakan bateri akibat kecuaian, dan aksesori hilang/rosak. Kerosakan hanya dilindungi jika melibatkan perlanggaran dua kenderaan bergerak. Jika kenderaan rosak ketika parkir, penyewa bertanggungjawab sepenuhnya. Bahagian bawah, cermin dan bumbung tidak dilindungi.",
            sec7_sub2: "Kemalangan & Yuran Pengurusan",
            sec7_p2: "Laporan polis mesti dibuat dalam masa 24 jam. Jika berlaku kemalangan, syarikat boleh mengenakan caj pengurusan (meliputi urusan insurans, komunikasi, kehilangan pendapatan) antara <strong>RM1,000 &ndash; RM5,000</strong> bergantung kepada kenderaan. Jika tuntutan pihak ketiga gagal, kos ditanggung penyewa.",
            sec8_title: "Terma Tambahan, Pemulangan & Pembatalan",
            sec8_sub1: "Minyak",
            sec8_p1: "Kenderaan mesti dipulangkan dengan paras minyak sama. Caj sehingga RM300 dikenakan jika kurang.",
            sec8_sub2: "Kebersihan",
            sec8_p2: "Jika terlalu kotor &rarr; caj RM300. Merokok / bawa haiwan &rarr; penalti RM500.",
            sec8_sub3: "Saman & Tiket Trafik",
            sec8_p3: "Semua saman tanggungjawab penyewa. Lewat bayar &rarr; penalti RM300.",
            sec8_sub4: "Had Laju",
            sec8_p4: "Lebuh raya: 110 km/j. Jalan biasa: 90 km/j.",
            sec8_sub5: "Polisi Pembatalan",
            sec8_l1: "24 jam sebelum: Full refund",
            sec8_l2: "Kurang 24 jam / No show: Tiada refund",
            sec8_l3: "Tukar tarikh: Tertakluk kepada kekosongan",
            sec8_l4: "Syarikat batal: Refund penuh atau reschedule",
            sec8_sub6: "Pemulangan & Penamatan",
            sec8_p5: "Maklum sekurang-kurangnya 12 jam sebelum pulangkan kereta. Syarikat boleh tamatkan sewaan serta-merta jika berlaku salah guna. Deposit boleh hangus.",
            sec8_sub7: "Kegunaan Jenayah",
            sec8_p6: "Jika digunakan untuk jenayah, penyewa bertanggungjawab penuh atas nilai kenderaan.",
            sec8_sub9: "Tunggakan Bayaran",
            sec8_p8: "Jika terdapat bayaran tertunggak yang tidak dijelaskan, nama penyewa boleh disenarai hitam dalam sistem CTOS dan tindakan lanjut boleh diambil oleh syarikat.",
            sec8_sub8: "Data Peribadi & Penafian",
            sec8_p7: "Data boleh dikongsi dengan agensi berkaitan untuk tujuan kutipan hutang. Dengan menyewa, penyewa bersetuju dengan semua terma dan syarat.",
            footer_copy: "Hak Cipta Terpelihara.",
        },
    };

    const htmlKeys = [
        "sec2_l2",
        "sec2_l3",
        "sec2_l4",
        "sec4_p1",
        "sec4_p4",
        "sec5_p1",
        "sec5_p2",
        "sec5_p3",
        "sec7_l1",
        "sec7_l2",
        "sec7_l3",
        "sec7_l4",
        "sec7_p1",
        "sec7_p2",
        "sec8_p2",
        "sec8_p3",
    ];

    const languageController = createLanguageController({
        defaultLanguage: "ms",
        translations,
        desktopToggleId: "lang-toggle",
        htmlKeys,
    });

    document.querySelectorAll("[data-language-toggle]").forEach((button) => {
        button.addEventListener("click", () => {
            languageController.toggleLanguage();
        });
    });

    setCurrentYear();
    languageController.updateUI();
})();
